#spring.datasource.url=jdbc:h2:mem:eventManagerdb
spring.datasource.url=jdbc:postgresql://ep-nameless-river-ae8ewar2.c-2.us-east-2.aws.neon.tech/eventManagerdb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jW0lNabEDAG8
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ThisIsAVerySecureJwtSecretKeyThatIsDefinitelyLongEnoughToMeetThe512BitRequirementForHS512AlgorithmCompliance
jwt.expiration=3600000