spring.application.name=api
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.secret=ThisIsAVerySecureJwtSecretKeyThatIsDefinitelyLongEnoughToMeetThe512BitRequirementForHS512AlgorithmCompliance
jwt.expiration=3600000